name: My Workflow
#final test 2.0
#trigger`
on:
  push:
    branches:
    - "v[0-9]+.[0-9]+"

#jobs in the workflow
jobs:
 #job name
  MyFirstJob:
    #OS that this workflow will be running on
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"

    steps:
    - name: Checkout the correct branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    
    - name: Install Railway
      run: npm i -g @railway/cli
  
    - name: Deploy to Railway
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RWY_TOKEN }}
    
    - name: Get deployment link
      id: linkgen
      run: echo "url=$(cat miscellaneous.json)" >> $GITHUB_OUTPUT
        
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
    
    - name: Slack notification
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.TEST_HOOK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nLu Bo Zhen"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\nA0265077X"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\n<mailto:e1045752@u.nus.edu|e1045752@u.nus.edu>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n<${{ github.repositoryUrl }}>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\n<${{ fromJson(steps.linkgen.outputs.url).deployUrl }}>"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ fromJson(steps.linkgen.outputs.url).deployUrl }}|Open Application>"
                }
              }
            ]
          }